// DECCAN II — regenerate rules/CARDS.md from sim/cards.mjs.
//
// DECISIONS.md D004: card data has exactly one source. rules/CARDS.md is output, never input.
// The old project's most persistent defect was a rulebook and an implementation describing
// different games; generation is what closes it.
//
//   node sim/cardsdoc.mjs        (npm run cards)

import { writeFileSync } from "node:fs";
import {
  FACTIONS, ARCHETYPES, TYPES, BEATS, GLYPH,
  UNITS_PER_FACTION, UNITS_PER_TYPE, TOTAL_STRENGTH, STRENGTH_MULTISET, VICTORY_TARGET,
  typeTotals,
} from "./cards.mjs";

const out = [];
const w = (s = "") => out.push(s);

w("# DECCAN II — Card List");
w();
w("<!-- GENERATED FROM sim/cards.mjs BY `npm run cards`. DO NOT EDIT THIS FILE. -->");
w();
w(`**${FACTIONS.length} factions · ${UNITS_PER_FACTION} units each · ` +
  `${FACTIONS.length * UNITS_PER_FACTION} cards in the box.**`);
w();
w("## The counter cycle");
w();
for (const t of TYPES) w(`* **${t}** beats **${BEATS[t]}**`);
w();
w("A countered unit loses its front whatever its strength. Otherwise the higher strength wins.");
w();

w("## The chassis");
w();
w("Every faction holds the **same twelve numbers** and **four units of each type**. The only");
w("thing that differs between factions is which type each number is printed on.");
w();
w(`> ${STRENGTH_MULTISET.join(" · ")}    (${UNITS_PER_FACTION} units, ${TOTAL_STRENGTH} strength, ` +
  `${UNITS_PER_TYPE} of each type)`);
w();
w("Factions are built from **archetypes**, each appearing in all three arms. The first group of");
w("numbers goes to the faction's lead arm, the second to the next arm round the cycle, the third");
w("to the last.");
w();
w("| Archetype | Lead arm | Next | Last |");
w("| --- | --- | --- | --- |");
for (const [name, g] of Object.entries(ARCHETYPES))
  w(`| ${name} | ${g[0].join(" · ")} | ${g[1].join(" · ")} | ${g[2].join(" · ")} |`);
w();

w("## Victory target");
w();
w("| Players | " + Object.keys(VICTORY_TARGET).join(" | ") + " |");
w("| --- |" + Object.keys(VICTORY_TARGET).map(() => " ---: |").join(""));
w("| Points to win | " + Object.values(VICTORY_TARGET).join(" | ") + " |");
w();

w("## The factions");
for (const f of FACTIONS) {
  const tot = typeTotals(f);
  w();
  w(`### ${f.name}`);
  w();
  w(`*${f.era}* — ${f.blurb}`);
  w();
  w(`**${f.archetype}**, lead arm **${f.lead}**.`);
  w();
  w("| Arm | Units | Total |");
  w("| --- | --- | ---: |");
  for (const t of TYPES) {
    const us = f.units.filter((u) => u.t === t).map((u) => u.s).sort((a, b) => a - b);
    w(`| ${t} | ${us.map((s) => `**${GLYPH[t]}${s}**`).join(" · ")} | ${tot[t]} |`);
  }
}

w();
w("## Print sheet");
w();
w("One line per card. `H`/`F`/`G` is the type, the number is the printed strength.");
w();
w("| Faction | Cards |");
w("| --- | --- |");
for (const f of FACTIONS)
  w(`| ${f.name} | ${f.units.slice().sort((a, b) => TYPES.indexOf(a.t) - TYPES.indexOf(b.t) || a.s - b.s)
    .map((u) => `${GLYPH[u.t]}${u.s}`).join(" ")} |`);
w();

writeFileSync(new URL("../rules/CARDS.md", import.meta.url), out.join("\n"));
console.log(`wrote rules/CARDS.md — ${FACTIONS.length} factions, ${FACTIONS.length * UNITS_PER_FACTION} cards`);
