// DECCAN — regenerate rules/CARDS.md from sim/cards.mjs.
//
// DECISIONS.md D004: card data has exactly one source. rules/CARDS.md is output, never input.
//
//   node sim/cardsdoc.mjs        (npm run cards)

import { writeFileSync } from "node:fs";
import { ARMS, FORCE, BROKERS, FACTIONS, GLYPH, PREY, VICTORY_TARGET } from "./cards.mjs";

const out = [];
const w = (s = "") => out.push(s);
const nextArm = (a) => ARMS[(ARMS.indexOf(a) + 1) % 5];
const order = ["ELEPHANT", "CANNON", "HORSEMAN", "RIFLEMAN", "WARRIOR"];
const unitOf = (a) => FORCE.find((u) => u.arm === a);
const hand = (f) => order.flatMap((a) => Array(f.counts[a]).fill(GLYPH[a] + unitOf(a).s));

w("# DECCAN — Card List");
w();
w("<!-- GENERATED FROM sim/cards.mjs BY `npm run cards`. DO NOT EDIT THIS FILE. -->");
w();
const handSize = FACTIONS[0].units.length;
const units = FACTIONS.reduce((s, f) => s + f.units.length, 0);
const supply = BROKERS.reduce((s, b) => s + b.copies, 0);
w(`**${FACTIONS.length} rulers × ${handSize} units = ${units} cards, plus ${supply} Power Brokers — ${units + supply} in the box.**`);
w();

w("## The ring");
w();
w("> " + ARMS.join(" → ") + " → back to " + ARMS[0]);
w();
w("Each arm cancels the **next two** along the ring, and is cancelled by the two behind it.");
w();
w("| Arm | Force unit | Power Broker | cancels | cancelled by |");
w("| --- | --- | --- | --- | --- |");
for (const a of order) {
  const f = unitOf(a), b = BROKERS.find((x) => x.arm === a);
  const killers = ARMS.filter((k) => PREY[k].includes(a));
  w(`| **${a}** | ${f.name} **${f.s}** | ${b.name} **${b.s}** | ${PREY[a].join(", ")} | ${killers.join(", ")} |`);
}
w();
w("Force strengths are **odd** and Power Broker strengths **even**, so a Force unit and a broker");
w("can never tie, and every broker is exactly one better than its own arm's Force unit.");
w();

w("## Victory");
w();
w("| Players | " + Object.keys(VICTORY_TARGET).join(" | ") + " |");
w("| --- |" + Object.keys(VICTORY_TARGET).map(() => " ---: |").join(""));
w("| Points to win | " + Object.values(VICTORY_TARGET).join(" | ") + " |");
w();

w("## The eight rulers");
w();
w(`Each holds ${handSize} units. Every ruler holds at least one of every arm, so every ruler can`);
w("answer every arm; what differs is where its spare cards sit. Note that most rulers carry the");
w("arm that answers their own — the Sultan's elephants are cancelled by warriors, so the Sultan");
w("fields warriors. The counts are set by measurement, one ruler at a time, not by a formula.");
w();
w("| Ruler | | Force | Total |");
w("| --- | --- | --- | ---: |");
for (const f of FACTIONS) {
  // Describe the deck from its actual counts: every arm holding more than the 1-per-arm floor.
  const NUM = { 2: "two", 3: "three", 4: "four" };
  const lead = order.filter((a) => f.counts[a] > 1)
    .sort((a, b) => f.counts[b] - f.counts[a])
    .map((a) => `${NUM[f.counts[a]]} ${a.toLowerCase()}`).join(" + ");
  w(`| **${f.name}** | ${lead} | ${hand(f).join(" ")} | ${f.total} |`);
}
w();
for (const f of FACTIONS) w(`*${f.name} — ${f.era}.*  `);
w();

w("## The supply");
w();
w(`${BROKERS[0].copies} of each, ${supply} cards. Recruited by **losing** — one per defeated player,`);
w("whatever they committed.");
w();
w("| Power Broker | | Arm | Timing | Ability |");
w("| --- | ---: | --- | --- | --- |");
for (const b of order.map((a) => BROKERS.find((x) => x.arm === a)))
  w(`| **${b.name}** | ${b.s} | ${b.arm} | **${b.when}** | ${b.text} |`);
w();
w("**ON DEPLOY** — when the card is committed, before anything is revealed. Cancellation cannot");
w("stop it. **ON REVEAL** — the abilities step of the battle: the ring resolves first, so only");
w("survivors act. **ON DEFEAT** — after the ground is decided, if this card survived and its army");
w("did not take it.");
w();

w("## Print sheet");
w();
w("`E` elephant · `C` cannon · `H` horseman · `R` rifleman · `W` warrior. The number is strength.");
w();
w("| Deck | Cards |");
w("| --- | --- |");
for (const f of FACTIONS) w(`| ${f.name} | ${hand(f).join(" ")} |`);
for (const b of order.map((a) => BROKERS.find((x) => x.arm === a)))
  w(`| ${b.name} ×${b.copies} | ${GLYPH[b.arm]}${b.s} |`);
w();

writeFileSync(new URL("../rules/CARDS.md", import.meta.url), out.join("\n"));
console.log(`wrote rules/CARDS.md — ${FACTIONS.length} factions, ${units + supply} cards`);
